### ISSUE TITLE
Evaluate graph library multicore support introduced with DPDK 23.xx

### ISSUE THREAD

**Issue by byteocean** [ironcore-dev/dpservice#507] opened 2024-03-18 15:52 UTC
As dpservice has introduced DPDK 23.11 support, we could evaluate graph library multicore support introduced with its previous release, DPDK 23.07 (mcore dispatch).

https://doc.dpdk.org/guides/rel_notes/release_23_07.html

**Comment by guvenc** [comment] 2024-06-27 07:48
Duplicate of #123

**Closed by guvenc** 2024-06-27 07:48 UTC
Labels: enhancement, question
